#pragma once


#define HEIGHT_TITLE    19
#define WIDTH_ITEM      69
#define HEIGHT_ITEM     ((HEIGHT_SCREEN - HEIGHT_TITLE - 1) / 4)
#define HEIGHT_SIGNAL   ((HEIGHT_SCREEN - HEIGHT_TITLE) / 2)
#define WIDTH_SIGNAL    ((WIDTH_SCREEN - WIDTH_ITEM) - 1)
